{% set name = "antropy" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c234464e065a566eaff4d367db31c0983ef669803ba7c4e35c74e1518adee21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - numba

test:
  imports:
    - antropy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://raphaelvallat.com/antropy/build/html/index.html
  summary: Entropy and complexity of (EEG) time-series data in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/raphaelvallat/antropy

extra:
  recipe-maintainers:
    - raphaelvallat
    - larsoner
    - hoechenberger
