{% set name = "antropy" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6016e893acbb1d9bae6dd5b2d373d28dc759032bb4132436c76e887d1bd8c24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - numba
    - stochastic

test:
  imports:
    - antropy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://raphaelvallat.com/antropy/build/html/index.html
  summary: Entropy and complexity of (EEG) time-series data in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/raphaelvallat/antropy

extra:
  recipe-maintainers:
    - raphaelvallat
    - larsoner
    - hoechenberger
